[[cells]]
name = "ckb-auth"
enable_type_id = true
location = { file = "../../contracts/ckb-auth/auth" }

[[cells]]
name = "stealth-lock"
enable_type_id = true
location = { file = "../../build/release/stealth-lock" }

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x102a06dbe3aea7bbeada2977ad1d3ab6df4ab0da"
hash_type = "type"
