[[cells]]
name = "ckb-auth"
enable_type_id = true
location = { file = "../../contracts/ckb-auth/auth" }

[[cells]]
name = "stealth-lock"
enable_type_id = true
location = { file = "../../build/release/stealth-lock" }

[[cells]]
name = "ct-info-type"
enable_type_id = true
location = { file = "../../build/release/ct-info-type" }

[[cells]]
name = "ct-token-type"
enable_type_id = true
location = { file = "../../build/release/ct-token-type" }

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x64257f00b6b63e987609fa9be2d0c86d351020fb"
hash_type = "type"
